sudo: required
dist: bionic
language: cpp

env:
    - OF_VERS=7
    - OF_VERS=-dev

before_install:
    - sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
    - sudo add-apt-repository http://dl.openfoam.org/ubuntu
    - sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev"
    - sudo apt-get update -qq
    - sudo apt-get install -qq openfoam${OF_VERS}

install:
    - source /opt/openfoam${OF_VERS}/etc/bashrc
    
before_script:
    - source /opt/openfoam${OF_VERS}/etc/bashrc

script:
    - cd $TRAVIS_BUILD_DIR/pitzDaily_3d_01/
    - travis_wait 30 ./Allrun
    - ls
    - tail -n 100 log.simpleFoam
