#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


mpirun -n 36 -hostfile $HOME/hostfile -prefix /opt/amazon/openmpi simpleFoam -parallel >log.simpleFoam 2>&1

#------------------------------------------------------------------------------
